---

source_modules:
    - barbicanclient
    - ceilometer
    - ceilometerclient
    - cinder
    - cinderclient
    - glance
    - glance_store
    - glanceclient
    - heat
    - heat_cfntools
    - heatclient
    - horizon
    - keystone
    - keystoneauth1
    - keystoneclient
    - keystonemiddleware
    - neutron
    - neutron_fwaas
    - neutron_lbaas
    - neutronclient
    - nova
    - novaclient
    - openstack_auth
    - openstackclient
    - os_brick
    - os_client_config
    - oslo
    - oslo_cache
    - oslo_concurrency
    - oslo_config
    - oslo_context
    - oslo_db
    - oslo_i18n
    - oslo_log
    - oslo_messaging
    - oslo_middleware
    - oslo_policy
    - oslo_reports
    - oslo_rootwrap
    - oslo_serialization
    - oslo_service
    - oslo_utils
    - oslo_versionedobjects
    - oslo_vmware
    - osprofiler
    - packstack
    - pbr
    - saharaclient
    - swiftclient
    - troveclient
