---

- name: Install covarage
  hosts: "{{ test.hosts }}"
  become: true
  roles:
      - { role: activate, when: test.activate | default(False) }

- name: Collect coverage data from all nodes
  hosts: openstack_nodes
  gather_facts: no
  become: true
  roles:
      - { role: collect, when: test.collect | default(False) }

- name: Generate coverage report
  hosts: "{{ test.aggregator }}"
  gather_facts: no
  become: true
  roles:
      - { role: report, when: test.report | default(False) }

- name: Publish to SonarQube
  hosts: "{{ test.aggregator }}"
  gather_facts: no
  become: true
  roles:
      - { role: publish, when: test.publish | default(False) }
