---

- name: Install coverage
  import_playbook: install.yml
  when:
    - test.activate | default(False)
    - not test.containers

- name: Install coverage on containers
  import_playbook: install_containers.yml
  when:
    - test.activate | default(False)
    - test.containers

- name: Collect coverage data from all nodes
  hosts: openstack_nodes
  gather_facts: no
  become: true
  tasks:
    - name: Set install vars
      set_fact:
        dfg: "{{ test.dfg }}"

    - name: set os_version fact
      set_fact:
        os_version: "{{ test.openstack.version | openstack_release }}"

    - name: Collect coverage data from all nodes
      import_role:
        name: openstack-coverage
        tasks_from: collect.yml
      vars:
        aggregator: "{{ test.aggregator }}"
      when:
        - test.collect | default(False)
        - not test.containers

    - name: Collect coverage data from all containers on all nodes
      import_role:
        name: openstack-coverage
        tasks_from: collect_containers.yml
      vars:
        aggregator: "{{ test.aggregator }}"
      when:
        - test.collect | default(False)
        - test.containers

- name: Generate coverage report and Publish to SonarQube
  hosts: "{{ test.aggregator }}"
  gather_facts: no
  become: true
  tasks:
    - name: Generate coverage report
      import_role:
        name: openstack-coverage
        tasks_from: report.yml
      when: test.report | default(False)

    - name: Copy coverage report to storage
      import_role:
        name: openstack-coverage
        tasks_from: storage.yml
      when: test.get('storage', {}).activate | default(False)

    - name: Publish to SonarQube
      block:
        - name: Set Sonar server vars
          set_fact:
            sonar_url: "{{ test.sonar.url }}"
            sonar_login: "{{ test.sonar.login }}"
            sonar_project: "{{ test.sonar.project }}"

        - name: Set Sonar password
          set_fact:
            sonar_password: "{{ test.sonar.password }}"
          when: test.sonar.password | default(False)

        - name: include publish role
          import_role:
            name: openstack-coverage
            tasks_from: publish.yml

      when: test.publish | default(False)
