---

- name: Include source module vars
  include_vars:
    file: "dfg/{{ test.dfg }}.yml"

- name: Install pip
  become: yes
  easy_install:
    name: pip
    state: latest

- name: Install coverage
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
      - coverage

- name: install python-devel and gcc
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-devel
    - gcc

- name: get openstack-service command
  become: yes
  yum:
    name: openstack-utils
    state: present

- file:
    path: /coverage
    state: directory
    mode: 0777

- template:
    dest: "/coverage/.coveragerc"
    src: my.coveragerc.j2
    mode: 0644

- copy:
    dest: "/lib/python2.7/site-packages/sitecustomize.py"
    src: sitecustomize.py
    mode: 0644

#- copy:
#    dest: "/coverage/collect.sh"
#    src: collect.sh
#    mode: 0744

#- copy:
#    dest: /etc/cron.d/coverage-combine
#    src: coverage.cron
#    mode: 0644

# workaround due to the following bug:
# https://bugzilla.redhat.com/show_bug.cgi?id=1394689
- name: stop zaqar service
  become: yes
  shell: systemctl stop openstack-zaqar
  when: inventory_hostname == groups['undercloud'][0]

- name: restart all services to activate coverage
  become: yes
  ignore_errors: yes
  shell: openstack-service restart
  environment:
        COVERAGE_PROCESS_START: /coverage/.coveragerc

- name: start zaqar service
  become: yes
  shell: systemctl start openstack-zaqar
  environment:
        COVERAGE_PROCESS_START: /coverage/.coveragerc
  when: inventory_hostname == groups['undercloud'][0]