---

- name: Include source module vars
  include_vars:
    file: "dfg/{{ test.dfg }}.yml"

- include_tasks: "install_dependencies.yml"

- name: Create coverage folder
  file:
    path: /coverage
    state: directory
    mode: 0777

- name: Generate coveragerc configuration file
  template:
    dest: "/coverage/.coveragerc"
    src: my.coveragerc.j2
    mode: 0644

- name: Install sitecustomize.py
  copy:
    dest: "/lib/python2.7/site-packages/sitecustomize.py"
    src: sitecustomize.py
    mode: 0644

# increase neutron timeout on controllers to avoid failing when stopping services
- block:
  - name: Increase neutron server graceful_shutdown_timeout
    ini_file:
      path: /etc/neutron/neutron.conf
      section: DEFAULT
      option: graceful_shutdown_timeout
      value: 300
      backup: yes

  - name: Increase neutron server TimeoutStopSec
    ini_file:
      path: /usr/lib/systemd/system/neutron-server.service
      section: Service
      option: TimeoutStopSec
      value: 300
      backup: yes

  - name: daemon-reload
    shell: systemctl daemon-reload

  when: inventory_hostname in groups.get('controller', [])

# workaround due to the following bug:
# https://bugzilla.redhat.com/show_bug.cgi?id=1394689
- name: stop zaqar service
  shell: systemctl stop openstack-zaqar
  when: inventory_hostname in groups.get('undercloud', [])

- name: restart all services to activate coverage
  ignore_errors: yes
  shell: openstack-service restart

- name: start zaqar service
  shell: systemctl start openstack-zaqar
  when: inventory_hostname in groups.get('undercloud', [])