---

# workaround due to the following bug:
# https://bugzilla.redhat.com/show_bug.cgi?id=1394689
- name: stop zaqar service
  become: yes
  shell: systemctl stop openstack-zaqar
  when: inventory_hostname in groups.get('undercloud', [])

- name: stop all services so they write out data files
  shell: openstack-service stop
  ignore_errors: yes

- name: aggregate covereage data per host
  shell: coverage combine --append --rcfile=/coverage/.coveragerc
  args:
      chdir: /coverage

- block:
      - name: fetch coverage data to localhost
        fetch:
          src: /coverage/.coverage
          dest: .coverage.{{ inventory_hostname }}
          flat: yes

      - name: copy coverage data to {{ test.aggregator }}
        copy:
          src: .coverage.{{ inventory_hostname }}
          dest: /coverage/.coverage.{{ inventory_hostname }}
        delegate_to: "{{ test.aggregator }}"
  when: inventory_hostname != test.aggregator
