---

# workaround due to the following bug:
# https://bugzilla.redhat.com/show_bug.cgi?id=1394689
- name: stop zaqar service
  become: yes
  shell: systemctl stop openstack-zaqar
  when: inventory_hostname in groups.get('undercloud', [])

- name: stop all services so they write out data files
  shell: openstack-service stop
  ignore_errors: yes

- name: aggregate covereage data per host
  shell: coverage combine --append --rcfile=/coverage/.coveragerc
  args:
      chdir: /coverage

- name: copy coverage data to {{ test.aggregator }}
  synchronize:
      src: /coverage/.coverage
      dest: /coverage/.coverage.{{ inventory_hostname }}
      mode: pull
  when: inventory_hostname != test.aggregator
  delegate_to: "{{ test.aggregator }}"
