# rhos-release used for installing the rhos repos.
- block:
    - name: Install rhos-release
      become: yes
      package:
        name="http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm"

    - name: Execute rhos-release to install rhos repos
      vars:
        os_version_director: "{{ (os_version|int in [7, 8, 9]) | ternary(os_version + '-director', '') }}"
      become: yes
      shell: |
        /usr/bin/rhos-release -x
        /usr/bin/rhos-release {{ os_version }} {{ os_version_director }}
      args:
        warn: no
      changed_when: true
      tags:
        - skip_ansible_lint

    - name: enable yum-config-manager
      package:
        name: yum-utils
  when: install_rhos_repos

- name: install python-devel and gcc
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-devel
    - gcc

- name: Install pip
  easy_install:
    name: pip
    state: latest

- name: Install coverage
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
      - coverage

- name: get openstack-service command
  yum:
    name: openstack-utils
    state: present
