- name: add storage to host list
  add_host:
      name: "{{ test.storage.hostname.split('.')[0] | lower }}"
      groups: "storage"
      ansible_user: "{{ test.storage.user }}"
      ansible_ssh_pass: ""
      ansible_host: "{{ test.storage.hostname}}"
      ansible_ssh_private_key_file: "{{ test.storage.key }}"

- name: Get puddle version
  include_tasks: puddle-discovery.yml
  when: core_puddle is not defined

- name:
  set_fact:
      log_directory: "{{ test.storage.log.dir }}/{{ test.openstack.version }}/{{ core_puddle }}/{{ test.dfg }}/"
      job_name: "{{ test.jenkins.job.name }}_{{ test.jenkins.build.id }}"
      full_log_path: "{{ log_directory }}/coverage_data_file_{{ job_name }}"

- name: Check storage directory exists
  file:
      path: "{{ inventory_dir }}/collected_coverage_files/"
      state: directory
      recurse: yes
  delegate_to: localhost

- name: copy file to local
  fetch:
      src: "{{ coverage_results_dir }}/combined_data"
      dest: "{{ inventory_dir }}/collected_coverage_files/{{ job_name }}"
      flat: yes

- name: Check storage directory exists
  file:
      path: "{{ full_log_dir_path }}"
      state: directory
      recurse: yes
      mode: 0755
  delegate_to: "{{ groups.storage | first }}"

- name: copy coverage data from undercloud to selected storage
  copy:
      src: "{{ inventory_dir }}/collected_coverage_files/{{ job_name }}"
      dest: "{{ full_log_path }}"
      force: yes
  delegate_to: "{{ groups.storage | first }}"
