- name: add storage to host list
  add_host:
      name: "{{ test.storage.hostname.split('.')[0] | lower }}"
      groups: "storage"
      ansible_user: "{{ test.storage.user }}"
      ansible_host: "{{ test.storage.hostname}}"
      ansible_ssh_private_key_file: "{{ test.storage.key }}"

- name: Get puddle version
  include_tasks: puddle-discovery.yml
  when: core_puddle is not defined

- name: set fact log_directory
  set_fact:
      log_directory: "{{ test.storage.log.dir }}/{{ test.openstack.version }}/{{ core_puddle }}/{{ test.dfg }}/"

- name: set fact job_name
  set_fact:
      job_name: "{{ test.jenkins.job.name }}_{{ test.jenkins.build.id }}"

- name: set fact full_log_path
  set_fact:
      full_log_path: "{{ log_directory }}/coverage_data_file_{{ job_name }}"

- name: Check storage directory exists
  file:
      path: "{{ inventory_dir }}/collected_coverage_files/"
      state: directory
      recurse: yes
  become: no
  delegate_to: localhost

- name: aggregate all covereage data
  shell: coverage combine --append --rcfile={{ coveragerc_path }}
  args:
      chdir: /coverage
  ignore_errors: yes

- name: copy file to local
  fetch:
      src: "/coverage/.coverage"
      dest: "{{ inventory_dir }}/collected_coverage_files/{{ job_name }}"
      flat: yes

- block:
  - name: Check storage directory exists
    file:
        path: "{{ log_directory }}"
        state: directory
        recurse: yes
        mode: 0755

  - name: copy coverage data from undercloud to selected storage
    copy:
        src: "{{ inventory_dir }}/collected_coverage_files/{{ job_name }}"
        dest: "{{ full_log_path }}"
        force: yes
  become: no
  delegate_to: "{{ groups.storage | first }}"
